version: '3.7'

services:
  mysqldb:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'authentication-node-react'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'lmao'
      MYSQL_ROOT_PASSWORD: 'lmaoroot'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - authentication-network

volumes:
  mysql-data:

networks:
  authentication-network:
    name: authentication-network